language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: s3
  access_key_id: AKIA5VS7GZDFAWALRKM7
  secret_access_key: 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
  bucket: mbendatravis
  local_dir: build
  acl: public_read